In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('./emails.csv', sep=',')
df.head()

                      email
0  jbechtelar@mcdermott.com
1          vyundt@yahoo.com
2       ariane78@sporer.net
3  brekke.crystel@gmail.com
4     egerhold@leuschke.com

Podemos usar o método extract para extrair o nome do email, o provedor e o *top level domain* da coluna email usando uma expressão regular.

In [3]:
(
    df
    .email
    .str
    .extract(r'([\w\.]+)@([\w]+)\.(\w+)')
    .rename(columns={0: 'user', 1: 'domain', 2: 'ext'})
)

                    user       domain   ext
0             jbechtelar    mcdermott   com
1                 vyundt        yahoo   com
2               ariane78       sporer   net
3         brekke.crystel        gmail   com
4               egerhold     leuschke   com
5               leonie55   vandervort   com
6   runolfsdottir.melany        stark   biz
7                glarson      hotmail   com
8                odell82        gmail   com
9           brain.heller        yahoo   com
10         haag.leonardo   vandervort   org
11              pcormier  greenfelder   com
12             lincoln49        yahoo   com
13        chanelle.mertz          toy   com
14         fausto.conroy        feest  info
15               ilarson       walker   com
16              kattie44      treutel   com
17                zkozey      oreilly   net
18                 hal56         batz   com
19         claire.durgan        zieme   org